public with sharing class TheApexClass {
    public TheApexClass() {
        

    //Check if an account is overdrawn and change the status of the account accordingly
    //If account balance equals zero or greater
    
    
    if (account.balance < 0){
        
    };
    //If not, update account to say 'in-debt'
    system.debug('Warning! The balance is now negative and the account is in debt.');

    //Create a new transaction relating to the account.
    
    //Update the account based on all related transactions to show current balance
    
    
    }


    void isAccountOverDrawn( Account.name ){
        if(Account.balance < 0) {
        Account.name //If account is negative...
        Account.name //Change status
        //Give warning


        }

    }
    
    void createNewTransaction(){


    }





}
